var wms_layers = [];
var baseLayer = new ol.layer.Group({
    'title': '',
    layers: [
new ol.layer.Tile({
    'title': 'OSM',
    'type': 'base',
    source: new ol.source.OSM()
})
]
});
var format_amenity_school_0 = new ol.format.GeoJSON();
var features_amenity_school_0 = format_amenity_school_0.readFeatures(json_amenity_school_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_amenity_school_0 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_amenity_school_0.addFeatures(features_amenity_school_0);var lyr_amenity_school_0 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_amenity_school_0, 
                style: style_amenity_school_0,
                title: '<img src="styles/legend/amenity_school_0.png" /> amenity_school'
            });var format_amenity_school_1 = new ol.format.GeoJSON();
var features_amenity_school_1 = format_amenity_school_1.readFeatures(json_amenity_school_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_amenity_school_1 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_amenity_school_1.addFeatures(features_amenity_school_1);var lyr_amenity_school_1 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_amenity_school_1, 
                style: style_amenity_school_1,
                title: '<img src="styles/legend/amenity_school_1.png" /> amenity_school'
            });var format_Schools_2 = new ol.format.GeoJSON();
var features_Schools_2 = format_Schools_2.readFeatures(json_Schools_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Schools_2 = new ol.source.Vector({
    attributions: [new ol.Attribution({html: '<a href=""></a>'})],
});
jsonSource_Schools_2.addFeatures(features_Schools_2);var lyr_Schools_2 = new ol.layer.Vector({
                declutter: true,
                source:jsonSource_Schools_2, 
                style: style_Schools_2,
                title: '<img src="styles/legend/Schools_2.png" /> Schools'
            });

lyr_amenity_school_0.setVisible(true);lyr_amenity_school_1.setVisible(true);lyr_Schools_2.setVisible(true);
var layersList = [baseLayer,lyr_amenity_school_0,lyr_amenity_school_1,lyr_Schools_2];
lyr_amenity_school_0.set('fieldAliases', {'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'amenity': 'amenity', 'name': 'name', 'building': 'building', 'crossing': 'crossing', 'highway': 'highway', 'phone': 'phone', 'barrier': 'barrier', 'addr_house': 'addr_house', 'name_en': 'name_en', 'addr_postc': 'addr_postc', 'opening_ho': 'opening_ho', 'addr_stree': 'addr_stree', 'website': 'website', 'addr_city': 'addr_city', 'contact_em': 'contact_em', 'descriptio': 'descriptio', 'addr_state': 'addr_state', 'addr_count': 'addr_count', 'name_ne': 'name_ne', 'horse': 'horse', 'bicycle': 'bicycle', 'motorcycle': 'motorcycle', 'motorcar': 'motorcar', 'foot': 'foot', 'office': 'office', 'int_name': 'int_name', 'designatio': 'designatio', 'wheelchair': 'wheelchair', 'toilets_wh': 'toilets_wh', 'shop': 'shop', 'operator': 'operator', 'email': 'email', 'addr_hou_1': 'addr_hou_1', 'history': 'history', 'operator_t': 'operator_t', 'student_co': 'student_co', 'addr_hamle': 'addr_hamle', 'name_hi': 'name_hi', 'name_es': 'name_es', 'addr_place': 'addr_place', 'contact_ph': 'contact_ph', 'ref': 'ref', 'power': 'power', 'personnel_': 'personnel_', 'isced_leve': 'isced_leve', 'building_c': 'building_c', 'name_tr': 'name_tr', 'access': 'access', 'motor_vehi': 'motor_vehi', 'denominati': 'denominati', });
lyr_amenity_school_1.set('fieldAliases', {'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'personnel_': 'personnel_', 'amenity': 'amenity', 'name': 'name', 'operator_t': 'operator_t', 'isced_leve': 'isced_leve', 'building_c': 'building_c', 'student_co': 'student_co', 'operator': 'operator', 'addr_city': 'addr_city', 'addr_stree': 'addr_stree', 'addr_place': 'addr_place', 'opening ti': 'opening ti', });
lyr_Schools_2.set('fieldAliases', {'full_id': 'full_id', 'osm_id': 'osm_id', 'osm_type': 'osm_type', 'floor_mate': 'floor_mate', 'amenity': 'amenity', 'operator_t': 'operator_t', 'building_a': 'building_a', 'physical_c': 'physical_c', 'building_c': 'building_c', 'building_o': 'building_o', 'building_b': 'building_b', 'building_1': 'building_1', 'retrofit': 'retrofit', 'building_l': 'building_l', 'isced_leve': 'isced_leve', 'start_date': 'start_date', 'type': 'type', 'building_s': 'building_s', 'personnel_': 'personnel_', 'building_2': 'building_2', 'oid': 'oid', 'phone': 'phone', 'building': 'building', 'shape_plan': 'shape_plan', 'name': 'Name', 'roof_shape': 'roof_shape', 'roof_mater': 'roof_mater', 'occupant_d': 'occupant_d', 'building_3': 'building_3', 'seismic_re': 'seismic_re', 'student_co': 'student_co', 'shape_elev': 'shape_elev', 'operator': 'operator', 'occupant_m': 'occupant_m', 'occupant_n': 'occupant_n', 'column_siz': 'column_siz', 'occupant_e': 'occupant_e', 'roof_colou': 'roof_colou', 'name_ne': 'name_ne', 'old_name': 'old_name', 'wheelchair': 'wheelchair', 'toilets_wh': 'toilets_wh', 'opening_ho': 'opening_ho', 'alt_name': 'alt_name', 'number_of_': 'number_of_', 'addr_city': 'addr_city', 'addr_place': 'addr_place', 'addr_stree': 'addr_stree', 'addr_postc': 'addr_postc', 'addr_count': 'addr_count', 'barrier': 'barrier', 'Household': 'Household', 'Househol_1': 'Househol_1', 'name_hi': 'name_hi', 'building_g': 'building_g', 'roof_mat_1': 'roof_mat_1', 'building_u': 'building_u', 'floor_ma_1': 'floor_ma_1', 'addr_house': 'addr_house', 'samakhusi-': 'samakhusi-', 'addr_tole': 'addr_tole', 'facility': 'facility', 'openning h': 'openning h', 'addr_ward': 'addr_ward', 'addr_hou_1': 'addr_hou_1', 'name_en': 'name_en', 'idp_status': 'idp_status', 'idp_camp_s': 'idp_camp_s', 'damage_eve': 'damage_eve', 'municipali': 'municipali', 'location': 'location', 'ward': 'ward', 'website': 'website', 'email': 'email', 'designatio': 'designatio', 'contact_we': 'contact_we', 'management': 'management', 'Househol_2': 'Househol_2', 'history': 'history', 'addr_hamle': 'addr_hamle', 'facebook': 'facebook', 'wikipedia': 'wikipedia', 'contact_ph': 'contact_ph', 'wikidata': 'wikidata', 'addr_name': 'addr_name', 'place': 'place', 'infrastruc': 'infrastruc', 'city': 'city', 'godawari m': 'godawari m', 'contact': 'contact', 'establishe': 'establishe', 'number_o_1': 'number_o_1', 'level': 'level', });
lyr_amenity_school_0.set('fieldImages', {'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'amenity': 'TextEdit', 'name': 'TextEdit', 'building': 'TextEdit', 'crossing': 'TextEdit', 'highway': 'TextEdit', 'phone': 'TextEdit', 'barrier': 'TextEdit', 'addr_house': 'TextEdit', 'name_en': 'TextEdit', 'addr_postc': 'TextEdit', 'opening_ho': 'TextEdit', 'addr_stree': 'TextEdit', 'website': 'TextEdit', 'addr_city': 'TextEdit', 'contact_em': 'TextEdit', 'descriptio': 'TextEdit', 'addr_state': 'TextEdit', 'addr_count': 'TextEdit', 'name_ne': 'TextEdit', 'horse': 'TextEdit', 'bicycle': 'TextEdit', 'motorcycle': 'TextEdit', 'motorcar': 'TextEdit', 'foot': 'TextEdit', 'office': 'TextEdit', 'int_name': 'TextEdit', 'designatio': 'TextEdit', 'wheelchair': 'TextEdit', 'toilets_wh': 'TextEdit', 'shop': 'TextEdit', 'operator': 'TextEdit', 'email': 'TextEdit', 'addr_hou_1': 'TextEdit', 'history': 'TextEdit', 'operator_t': 'TextEdit', 'student_co': 'TextEdit', 'addr_hamle': 'TextEdit', 'name_hi': 'TextEdit', 'name_es': 'TextEdit', 'addr_place': 'TextEdit', 'contact_ph': 'TextEdit', 'ref': 'TextEdit', 'power': 'TextEdit', 'personnel_': 'TextEdit', 'isced_leve': 'TextEdit', 'building_c': 'TextEdit', 'name_tr': 'TextEdit', 'access': 'TextEdit', 'motor_vehi': 'TextEdit', 'denominati': 'TextEdit', });
lyr_amenity_school_1.set('fieldImages', {'full_id': 'TextEdit', 'osm_id': 'TextEdit', 'osm_type': 'TextEdit', 'personnel_': 'TextEdit', 'amenity': 'TextEdit', 'name': 'TextEdit', 'operator_t': 'TextEdit', 'isced_leve': 'TextEdit', 'building_c': 'TextEdit', 'student_co': 'TextEdit', 'operator': 'TextEdit', 'addr_city': 'TextEdit', 'addr_stree': 'TextEdit', 'addr_place': 'TextEdit', 'opening ti': 'TextEdit', });
lyr_Schools_2.set('fieldImages', {'full_id': 'Hidden', 'osm_id': 'Hidden', 'osm_type': 'Hidden', 'floor_mate': 'Hidden', 'amenity': 'Hidden', 'operator_t': 'Hidden', 'building_a': 'Hidden', 'physical_c': 'Hidden', 'building_c': 'Hidden', 'building_o': 'Hidden', 'building_b': 'Hidden', 'building_1': 'Hidden', 'retrofit': 'Hidden', 'building_l': 'Hidden', 'isced_leve': 'Hidden', 'start_date': 'Hidden', 'type': 'Hidden', 'building_s': 'Hidden', 'personnel_': 'Hidden', 'building_2': 'Hidden', 'oid': 'Hidden', 'phone': 'Hidden', 'building': 'Hidden', 'shape_plan': 'Hidden', 'name': 'TextEdit', 'roof_shape': 'Hidden', 'roof_mater': 'Hidden', 'occupant_d': 'Hidden', 'building_3': 'Hidden', 'seismic_re': 'Hidden', 'student_co': 'Hidden', 'shape_elev': 'Hidden', 'operator': 'Hidden', 'occupant_m': 'Hidden', 'occupant_n': 'Hidden', 'column_siz': 'Hidden', 'occupant_e': 'Hidden', 'roof_colou': 'Hidden', 'name_ne': 'Hidden', 'old_name': 'Hidden', 'wheelchair': 'Hidden', 'toilets_wh': 'Hidden', 'opening_ho': 'Hidden', 'alt_name': 'Hidden', 'number_of_': 'Hidden', 'addr_city': 'Hidden', 'addr_place': 'Hidden', 'addr_stree': 'Hidden', 'addr_postc': 'Hidden', 'addr_count': 'Hidden', 'barrier': 'Hidden', 'Household': 'Hidden', 'Househol_1': 'Hidden', 'name_hi': 'Hidden', 'building_g': 'Hidden', 'roof_mat_1': 'Hidden', 'building_u': 'Hidden', 'floor_ma_1': 'Hidden', 'addr_house': 'Hidden', 'samakhusi-': 'Hidden', 'addr_tole': 'Hidden', 'facility': 'Hidden', 'openning h': 'Hidden', 'addr_ward': 'Hidden', 'addr_hou_1': 'Hidden', 'name_en': 'Hidden', 'idp_status': 'Hidden', 'idp_camp_s': 'Hidden', 'damage_eve': 'Hidden', 'municipali': 'Hidden', 'location': 'Hidden', 'ward': 'Hidden', 'website': 'Hidden', 'email': 'Hidden', 'designatio': 'Hidden', 'contact_we': 'Hidden', 'management': 'Hidden', 'Househol_2': 'Hidden', 'history': 'Hidden', 'addr_hamle': 'Hidden', 'facebook': 'Hidden', 'wikipedia': 'Hidden', 'contact_ph': 'Hidden', 'wikidata': 'Hidden', 'addr_name': 'Hidden', 'place': 'Hidden', 'infrastruc': 'Hidden', 'city': 'Hidden', 'godawari m': 'Hidden', 'contact': 'Hidden', 'establishe': 'Hidden', 'number_o_1': 'Hidden', 'level': 'Hidden', });
lyr_amenity_school_0.set('fieldLabels', {'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'amenity': 'no label', 'name': 'no label', 'building': 'no label', 'crossing': 'no label', 'highway': 'no label', 'phone': 'no label', 'barrier': 'no label', 'addr_house': 'no label', 'name_en': 'no label', 'addr_postc': 'no label', 'opening_ho': 'no label', 'addr_stree': 'no label', 'website': 'no label', 'addr_city': 'no label', 'contact_em': 'no label', 'descriptio': 'no label', 'addr_state': 'no label', 'addr_count': 'no label', 'name_ne': 'no label', 'horse': 'no label', 'bicycle': 'no label', 'motorcycle': 'no label', 'motorcar': 'no label', 'foot': 'no label', 'office': 'no label', 'int_name': 'no label', 'designatio': 'no label', 'wheelchair': 'no label', 'toilets_wh': 'no label', 'shop': 'no label', 'operator': 'no label', 'email': 'no label', 'addr_hou_1': 'no label', 'history': 'no label', 'operator_t': 'no label', 'student_co': 'no label', 'addr_hamle': 'no label', 'name_hi': 'no label', 'name_es': 'no label', 'addr_place': 'no label', 'contact_ph': 'no label', 'ref': 'no label', 'power': 'no label', 'personnel_': 'no label', 'isced_leve': 'no label', 'building_c': 'no label', 'name_tr': 'no label', 'access': 'no label', 'motor_vehi': 'no label', 'denominati': 'no label', });
lyr_amenity_school_1.set('fieldLabels', {'full_id': 'no label', 'osm_id': 'no label', 'osm_type': 'no label', 'personnel_': 'no label', 'amenity': 'no label', 'name': 'no label', 'operator_t': 'no label', 'isced_leve': 'no label', 'building_c': 'no label', 'student_co': 'no label', 'operator': 'no label', 'addr_city': 'no label', 'addr_stree': 'no label', 'addr_place': 'no label', 'opening ti': 'no label', });
lyr_Schools_2.set('fieldLabels', {'name': 'header label', });
lyr_Schools_2.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});